jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/viham1/test-spacy.git
  NER:
    resources:
      instance-type: A4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    outputs:
      model:
        type: dataset
        with:
          ref: demo-dataset
    with:
      image: viham1/spacy-gpu:latest
      script: |-
        cd /inputs/repo
        python task.py
        mv /model/model-last /outputs/model
        ls
  CreateModel:
    inputs:
      model: NER.outputs.model
    outputs:
      model-id:
        type: string
    uses: create-model@v1
    with:
      name: NER
      type: Custom #

